name: Validate

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "22 02 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "python_script"
